export const ProductActionTypes = {
    PRODUCT_LIST: 'PRODUCT_LIST',
    PRODUCT_CURRENT: 'PRODUCT_CURRENT',
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_FAILURE: 'PRODUCT_LIST_FAILURE',
}